shoplist = ['apple', 'mango', 'carrot', 'banana']
index = shoplist.index('carrot')
print(index)
shoplist.insert(3, 'peach')
print(shoplist)
shoplist.insert(0, 'beef')
print(shoplist)
shoplist.append('beef')
print(shoplist)
# remove는 처음부터 탐색해서 지우고 끝남, 마지막 beef는 지워지지 않음
shoplist.remove('beef')
print(shoplist)
shoplist.sort()
print(shoplist)
shoplist.sort(reverse=True)
print(shoplist)
shoplist.reverse()
print(shoplist)
print(len(shoplist))